"""Manuscript-ready Methods and Results text builders.

Extracted from ``app.py`` during the Phase 4 conservative refactor.
These are pure string builders with **no** Streamlit dependency: the
bilingual ``tr(en, pt) -> str`` helper and the currently selected
``language`` are passed in as explicit arguments.

No scientific methodology is changed by this extraction.  The only
content edit applied during the move is the user's naming rule from
this phase: literal occurrences of "STS" that refer to the score
have been replaced with "STS Score".  Proper-noun product names
("STS Risk Calculator") are left unchanged.
"""

from __future__ import annotations

from typing import Callable, Dict

TrFn = Callable[[str, str], str]


def build_methods_text(mode: str, language: str, tr: TrFn) -> str:
    """Methods section text in the chosen language and verbosity."""
    detailed = mode == tr("Detailed", "Detalhado")
    if language == "English":
        if detailed:
            return (
                "A retrospective analytical study was performed using matched data from the Preoperative, Pre-Echocardiogram, and Postoperative sheets. "
                "The primary endpoint was in-hospital or 30-day mortality, operationalized from the Postoperative Death field by considering Operative status and postoperative days 0 to 30 as events. "
                "Only records with Surgery and Procedure Date available were eligible, and matching across sheets was performed using patient identity and procedure date; these identifiers were used exclusively for linkage and not as predictors. "
                "AI Risk was trained exclusively with preoperative clinical, laboratory, echocardiographic, and procedural variables, excluding postoperative complications in order to avoid temporal leakage. Numeric variables were preprocessed with comma-decimal conversion (for Brazilian-format data), clinically impossible zeros treated as missing (e.g. BSA=0), median imputation, and StandardScaler normalization; valve severity variables were encoded ordinally (None < Trivial < Mild < Moderate < Severe); remaining categorical variables were encoded via TargetEncoder with automatic smoothing. Tree-based models (random forest, XGBoost, LightGBM, CatBoost) were post-hoc calibrated via Platt scaling (sigmoid method) to improve probability accuracy; calibration was applied inside each cross-validation fold so that calibrated out-of-fold predictions are free of information leakage. Candidate algorithms included logistic regression, random forest, multilayer perceptron, XGBoost, LightGBM, CatBoost, and a stacking ensemble. Model selection was based on stratified cross-validation grouped by patient, ensuring that the same patient never appeared simultaneously in training and testing folds. The final model was identified by jointly evaluating discrimination (AUC-ROC, AUPRC), calibration (Brier score), and net clinical benefit (decision curve analysis at 5\u201320% thresholds) \u2014 not by discrimination alone. Training data are drawn exclusively from this institution; applicability to other settings should be validated independently. "
                "Because the best-model selection algorithm ranks candidates on the same cross-validation partition used to report OOF metrics (AUC, AUPRC, Brier, calibration slope), the reported OOF estimates carry an optimism bias typical of in-sample model selection. OOF metrics are therefore presented as model-development results; the primary assessment of generalization is the Temporal Validation analysis on an independent cohort. Nested cross-validation was not implemented in this version; its addition is recommended if this work is extended to a multi-center cohort. "
                "EuroSCORE II was calculated from the published logistic equation, with operationalization of variables according to the available dataset. STS Score was obtained via automated interaction with the official STS Risk Calculator web application (https://acsdriskcalc.research.sts.org/), which does not offer a documented public API; preoperative data were mapped from the dataset and submitted via the calculator's WebSocket interface, for both batch analysis and individual prediction. "
                "The primary comparative analysis was the triple-cohort analysis including patients with simultaneous availability of AI Risk, EuroSCORE II, and STS Score. Complementary analyses may be conducted in specific subsets according to score availability, with explicit acknowledgment of sample differences. Discrimination was assessed by AUC-ROC and AUPRC. In the model leaderboard (internal comparison), sensitivity and specificity were computed at the optimal threshold determined by Youden's J index (J = sensitivity + specificity \u2212 1) for each model independently. In the triple-score comparison, a fixed clinical decision threshold (default 8%) was applied uniformly to all three scores. Calibration was assessed by visual calibration curve, calibration-in-the-large, calibration slope, Brier score, and the Hosmer-Lemeshow test (10 groups) as a complementary assessment. Formal ROC comparison included bootstrap-based delta AUC (2,000 resamples) with 95% confidence intervals and DeLong testing for correlated ROC curves. Clinical utility was assessed by decision curve analysis across risk thresholds from 5% to 20%, and reclassification was summarized by NRI (risk categories: low <5%, intermediate 5\u201315%, high >15%) and IDI as complementary analyses. Subgroup analyses were planned according to surgery type (valve, myocardial revascularization, aortic surgery, transplant/assist device, and mixed surgery) and clinical profile (age group, left ventricular ejection fraction category, renal function, and sex), with 95% confidence intervals by bootstrap."
            )
        return (
            "A retrospective comparison of AI Risk, EuroSCORE II, and STS Score was performed for in-hospital or 30-day mortality after cardiac surgery. "
            "AI Risk was validated by cross-validation grouped by patient, and model performance was evaluated through discrimination, calibration, formal ROC comparison, decision curve analysis, and reclassification metrics. Training data are drawn exclusively from this institution."
        )
    if detailed:
        return (
                "Foi realizada an\u00e1lise retrospectiva com dados pareados das abas Preoperative, Pre-Echocardiogram e Postoperative. "
                "O desfecho prim\u00e1rio foi mortalidade hospitalar ou em 30 dias, operacionalizada a partir do campo Death da aba Postoperative, considerando como evento os casos classificados como Operative ou com ocorr\u00eancia entre os dias 0 e 30 de p\u00f3s-operat\u00f3rio. "
                "Foram eleg\u00edveis apenas registros com Surgery e Procedure Date preenchidos, sendo o pareamento entre as abas realizado por identidade do paciente e data do procedimento; esses identificadores foram utilizados exclusivamente para vincula\u00e7\u00e3o interna, sem participa\u00e7\u00e3o como vari\u00e1veis preditoras. "
                "O AI Risk foi treinado exclusivamente com vari\u00e1veis pr\u00e9-operat\u00f3rias cl\u00ednicas, laboratoriais, ecocardiogr\u00e1ficas e de procedimento, sem inclus\u00e3o de complica\u00e7\u00f5es p\u00f3s-operat\u00f3rias, a fim de evitar vazamento temporal. Vari\u00e1veis num\u00e9ricas foram pr\u00e9-processadas com convers\u00e3o de v\u00edrgula decimal (para dados em formato brasileiro), zeros clinicamente imposs\u00edveis tratados como ausentes (ex: BSA=0), imputa\u00e7\u00e3o pela mediana e normaliza\u00e7\u00e3o StandardScaler; vari\u00e1veis de gravidade valvar foram codificadas ordinalmente (None < Trivial < Mild < Moderate < Severe); demais vari\u00e1veis categ\u00f3ricas foram codificadas via TargetEncoder com suaviza\u00e7\u00e3o autom\u00e1tica. Modelos baseados em \u00e1rvore (random forest, XGBoost, LightGBM, CatBoost) foram calibrados por Platt scaling (m\u00e9todo sigmoid) para melhorar a acur\u00e1cia das probabilidades; a calibra\u00e7\u00e3o foi aplicada dentro de cada fold da valida\u00e7\u00e3o cruzada para que as predi\u00e7\u00f5es out-of-fold calibradas sejam livres de vazamento de informa\u00e7\u00e3o. Foram avaliados regress\u00e3o log\u00edstica, random forest, multilayer perceptron, XGBoost, LightGBM, CatBoost e ensemble por stacking. A sele\u00e7\u00e3o do melhor modelo foi baseada em valida\u00e7\u00e3o cruzada estratificada e agrupada por paciente, garantindo que o mesmo paciente n\u00e3o estivesse simultaneamente em treino e teste. O modelo final foi identificado avaliando conjuntamente discrimina\u00e7\u00e3o (AUC-ROC, AUPRC), calibra\u00e7\u00e3o (Brier score) e benef\u00edcio cl\u00ednico l\u00edquido (decision curve analysis entre 5\u201320%) \u2014 n\u00e3o apenas a AUC. Os dados de treinamento s\u00e3o exclusivamente desta institui\u00e7\u00e3o; a aplicabilidade a outros contextos deve ser validada independentemente. "
                "Como o algoritmo de seleção do melhor modelo ranqueia os candidatos na mesma partição de validação cruzada utilizada para reportar as métricas OOF (AUC, AUPRC, Brier, slope de calibração), as estimativas OOF reportadas carregam um viés de otimismo típico da seleção de modelos in-sample. As métricas OOF são portanto apresentadas como resultados de desenvolvimento do modelo; a avaliação primária de generalização é a análise de Validação Temporal em uma coorte independente. A validação cruzada aninhada não foi implementada nesta versão; sua adição é recomendada caso este trabalho seja estendido a uma coorte multicêntrica. "
                "O EuroSCORE II foi calculado pela equa\u00e7\u00e3o log\u00edstica publicada, com operacionaliza\u00e7\u00e3o das vari\u00e1veis a partir da base dispon\u00edvel. O STS Score foi obtido via intera\u00e7\u00e3o automatizada com a calculadora web oficial do STS Risk Calculator (https://acsdriskcalc.research.sts.org/), que n\u00e3o disponibiliza uma API p\u00fablica documentada; os dados pr\u00e9-operat\u00f3rios foram mapeados da base e enviados pela interface WebSocket da calculadora, tanto para an\u00e1lise em lote quanto para predi\u00e7\u00e3o individual. "
                "A an\u00e1lise comparativa principal foi a coorte tripla, composta pelos pacientes com disponibilidade simult\u00e2nea de AI Risk, EuroSCORE II e STS Score. An\u00e1lises complementares poder\u00e3o ser conduzidas em subconjuntos espec\u00edficos, de acordo com a disponibilidade de cada escore, com explicita\u00e7\u00e3o das diferen\u00e7as amostrais. A discrimina\u00e7\u00e3o foi avaliada por AUC-ROC e AUPRC. No leaderboard de modelos (compara\u00e7\u00e3o interna), sensibilidade e especificidade foram calculadas no limiar \u00f3timo determinado pelo \u00edndice de Youden (J = sensibilidade + especificidade \u2212 1) para cada modelo independentemente. Na compara\u00e7\u00e3o tripla de escores, um limiar cl\u00ednico fixo de decis\u00e3o (padr\u00e3o 8%) foi aplicado uniformemente aos tr\u00eas escores. A calibra\u00e7\u00e3o foi avaliada por curva de calibra\u00e7\u00e3o visual, calibration-in-the-large, slope de calibra\u00e7\u00e3o, Brier score e teste de Hosmer-Lemeshow (10 grupos) como avalia\u00e7\u00e3o complementar. A compara\u00e7\u00e3o formal entre curvas ROC utilizou delta AUC por bootstrap (2.000 reamostras) com intervalos de confian\u00e7a de 95% e teste de DeLong para curvas correlacionadas. A utilidade cl\u00ednica foi avaliada por decision curve analysis em limiares de 5% a 20%, e a reclassifica\u00e7\u00e3o progn\u00f3stica foi resumida por NRI (categorias de risco: baixo <5%, intermedi\u00e1rio 5\u201315%, alto >15%) e IDI como an\u00e1lises complementares. Foram ainda planejadas an\u00e1lises por subgrupos segundo tipo de cirurgia (valvar, revasculariza\u00e7\u00e3o do mioc\u00e1rdio, cirurgia da aorta, transplante/assist device e cirurgia mista) e perfil cl\u00ednico (faixa et\u00e1ria, categoria de FEVE, fun\u00e7\u00e3o renal e sexo), com intervalos de confian\u00e7a de 95% por bootstrap."
        )
    return (
        "Foi realizada compara\u00e7\u00e3o retrospectiva entre AI Risk, EuroSCORE II e STS Score para mortalidade hospitalar ou em 30 dias ap\u00f3s cirurgia card\u00edaca. "
        "O AI Risk foi validado por valida\u00e7\u00e3o cruzada agrupada por paciente, e o desempenho foi avaliado por m\u00e9tricas de discrimina\u00e7\u00e3o, calibra\u00e7\u00e3o, compara\u00e7\u00e3o formal entre curvas ROC, decision curve analysis e reclassifica\u00e7\u00e3o. Os dados de treinamento s\u00e3o exclusivamente desta institui\u00e7\u00e3o."
    )


def build_results_text(
    mode: str,
    context: Dict[str, object],
    language: str,
    tr: TrFn,
) -> str:
    """Results section text in the chosen language and verbosity."""
    detailed = mode == tr("Detailed", "Detalhado")
    if language == "English":
        if detailed:
            return (
                f"In the primary triple-cohort analysis including patients with simultaneous availability of AI Risk, EuroSCORE II, and STS Score (n={context['n_triple']}), the best overall discrimination was observed for {context['best_auc_model']} with AUC-ROC={context['best_auc']:.3f}. "
                f"At the selected decision threshold of {context['threshold']:.2f}, the highest sensitivity was observed for {context['best_sens_model']}, whereas the highest specificity was observed for {context['best_spec_model']}. The highest positive predictive value was observed for {context['best_ppv_model']}, and the highest negative predictive value for {context['best_npv_model']}. "
                f"Regarding calibration, the best overall Brier score was observed for {context['best_brier_model']}. Formal comparison of ROC curves indicated that {context['formal_summary']} In terms of clinical utility, the highest mean net benefit between 5% and 20% was observed for {context['best_dca_model']}. Regarding reclassification, {context['reclass_summary']} Given the low event prevalence typical of cardiac surgical cohorts, AUPRC is reported alongside AUC-ROC as a more sensitive summary of performance for rare events. Overall, these findings indicate that model choice should not rely on discrimination alone, but also on calibration, threshold-dependent performance, and net clinical benefit."
            )
        return (
            f"In the primary triple cohort (n={context['n_triple']}), {context['best_auc_model']} showed the best discrimination, {context['best_brier_model']} the best calibration, and {context['best_dca_model']} the highest average net benefit between 5% and 20%."
        )
    if detailed:
        return (
            f"Na an\u00e1lise principal da coorte tripla, composta pelos pacientes com disponibilidade simult\u00e2nea de AI Risk, EuroSCORE II e STS Score (n={context['n_triple']}), a melhor discrimina\u00e7\u00e3o global foi observada em {context['best_auc_model']}, com AUC-ROC={context['best_auc']:.3f}. "
            f"No limiar de decis\u00e3o selecionado de {context['threshold']:.2f}, a maior sensibilidade foi observada em {context['best_sens_model']}, enquanto a maior especificidade foi observada em {context['best_spec_model']}. O maior valor preditivo positivo foi observado em {context['best_ppv_model']}, e o maior valor preditivo negativo em {context['best_npv_model']}. "
            f"Em rela\u00e7\u00e3o \u00e0 calibra\u00e7\u00e3o, o melhor desempenho global pelo Brier score foi observado em {context['best_brier_model']}. A compara\u00e7\u00e3o formal entre curvas ROC indicou que {context['formal_summary']} Em termos de utilidade cl\u00ednica, o maior benef\u00edcio l\u00edquido m\u00e9dio entre 5% e 20% foi observado em {context['best_dca_model']}. Em rela\u00e7\u00e3o \u00e0 reclassifica\u00e7\u00e3o, {context['reclass_summary']} Dada a baixa preval\u00eancia de eventos t\u00edpica de coortes cir\u00fargicas card\u00edacas, a AUPRC \u00e9 reportada junto \u00e0 AUC-ROC como um resumo mais sens\u00edvel do desempenho para eventos raros. Em conjunto, esses achados sugerem que a escolha do melhor modelo n\u00e3o deve se apoiar apenas na discrimina\u00e7\u00e3o, mas tamb\u00e9m na calibra\u00e7\u00e3o, no desempenho dependente do limiar e no benef\u00edcio cl\u00ednico l\u00edquido."
        )
    return (
        f"Na coorte tripla principal (n={context['n_triple']}), {context['best_auc_model']} apresentou a melhor discrimina\u00e7\u00e3o, {context['best_brier_model']} a melhor calibra\u00e7\u00e3o e {context['best_dca_model']} o maior benef\u00edcio l\u00edquido m\u00e9dio entre 5% e 20%."
    )
